### ISSUE TITLE
Memory leak: 2 calls to new without a delete

### ISSUE THREAD

**Issue by benstadin** [google/jwt_verify_lib#42]
There seem two calls to new Pubkey() without delete at those locations in jwks.cc:

https://github.com/google/jwt_verify_lib/blob/40e2cc938f4bcd059a97dc6c73f59ecfa5a71bac/src/jwks.cc#L396
https://github.com/google/jwt_verify_lib/blob/40e2cc938f4bcd059a97dc6c73f59ecfa5a71bac/src/jwks.cc#L456

**Comment by nareddyt** [comment]
CC @alexcope @qiwzhang

**Comment by qiwzhang** [comment]
PubkeyPtr is std::unique_ptr.

**Comment by benstadin** [comment]
Indeed. But in that case it should better be make_unique instead.

**Comment by qiwzhang** [comment]
We could, but I believe it is only available in certain gcc compiler.  I am not sure if we have compiler version requirement.

**Comment by benstadin** [comment]
I think most compilers supporting C++11 and all supporting C++14.
