### ISSUE TITLE
JWKS parsing,  should just ignore not-supported JWK

### ISSUE THREAD

**Issue by qiwzhang** [google/jwt_verify_lib#50]
As raised in https://github.com/google/jwt_verify_lib/issues/49#issuecomment-638362338

If a JWKS has multiple JWK,  now, it will just fail the JWKS parsing if one of them is not supported.  
This will have problem with new alg added in the JWKS server.  It is better to ignore these new JWK, and keep searching for the one it known.

**Comment by qiwzhang** [comment]
@jheiss,  could you help to make this change in a separate PR?
The change will be just remove this `break` [here](https://github.com/google/jwt_verify_lib/blob/master/src/jwks.cc#L462)

You do have a JWKS test with X25519 to add a unit-test for it.

**Comment by jheiss** [comment]
Sure, I'll take a crack at this.

**Comment by qiwzhang** [comment]
Thanks.

**Comment by jheiss** [comment]
I believe we have to do more than just remove the break. Just removing the break means that createFrom still returns an error if any unsupported JWK is encountered. I'm thinking that we want to return Status::Ok if at least one JWK is successfully read, otherwise return an error?

**Comment by qiwzhang** [comment]
Yes, we should do that.

**Comment by qiwzhang** [comment]
My idea is this [line](https://github.com/google/jwt_verify_lib/blob/master/src/jwks.cc#L547),  we should over-write the status to OK if there is at lease one valid key in the list.

**Comment by qiwzhang** [comment]
You may need another resetStatus() since updateStatus() only set non-OK status.
