### ISSUE TITLE
Update BoringSSL revision

### ISSUE THREAD

**Issue by davidben** [google/jwt_verify_lib#97]
The BoringSSL revision hasn't been updated since 2020. It seems this project tries to track Envoy, so probably should update it to match.
https://github.com/envoyproxy/envoy/blob/f4812764c43df5872fd773b25d399f7ff8fa4403/bazel/repository_locations.bzl#L113

Note BoringSSL now requires C++14 (consistent with https://github.com/google/oss-policies-info/blob/main/foundational-cxx-support-matrix.md, for reference Envoy requires C++17), so you may need to update your build. I _think_ it's just a matter of adding `build --cxxopt="--std=c++14"` to `.bazelrc`, but I don't really understand Bazel, so that might not be sufficient.

**Comment by nareddyt** [comment]
Thanks for the link to the support matrix. Good to see we don't need to update `clang` version, as our repo is pinned to `clang-13`.

In that case, the only change needed is C++ version. That should be fairly simple.
